[build]
  publish = "/"
  command = ""  # No build command needed for a static HTML site

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://www.cognitoforms.com; img-src 'self' data: https://via.placeholder.com; font-src 'self'; connect-src 'self'; frame-src https://www.cognitoforms.com;"