[build]
  publish = "/"
  command = ""  # No build command needed for a static HTML site

# Redirects and headers
# Redirect removed coaches portal pages to home
[[redirects]]
  from = "/coaches.html"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/coaches-portal.html"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://www.cognitoforms.com; img-src 'self' data: https://via.placeholder.com; font-src 'self'; connect-src 'self'; frame-src https://www.cognitoforms.com; object-src 'none'; base-uri 'self'; form-action 'self' https://www.cognitoforms.com;"